import sys
from PyQt6 import QtWidgets,QtWebEngineWidgets,QtCore
app =QtWidgets.QApplication(sys.argv)

window=QtWidgets.QWidget()
window.setWindowTitle("retumilo")
#label = QtWidgets.QLabel("Hello World!",parent=window)
#label.setWindowTitle("retumilo")
#label.show()
browser=QtWebEngineWidgets.QWebEngineView(parent=window)
browser.load(QtCore.QUrl("https://www.google.com"))
back_page_button=QtWidgets.QPushButton("back")
#back_page_button.setGeometry(0,0,100,50)
forward_page_button=QtWidgets.QPushButton("forward")
reload_page_button=QtWidgets.QPushButton("reload")
back_page_button.clicked.connect(browser.back)
forward_page_button.clicked.connect(browser.forward)
reload_page_button.clicked.connect(browser.reload)
back_page_button.setFixedSize(50,20)
forward_page_button.setFixedSize(50,20)
reload_page_button.setFixedSize(50,20)
b_layout=QtWidgets.QHBoxLayout()
#b_layout.addWidget(back_page_button,alignment=QtCore.Qt.AlignmentFlag.AlignLeft)
b_layout.addWidget(back_page_button)
b_layout.addWidget(forward_page_button)
b_layout.addWidget(reload_page_button)
b_layout.addStretch()
main_layout=QtWidgets.QVBoxLayout()
main_layout.addLayout(b_layout)
#layout.addWidget(back_page_button)
#layout.addWidget(forward_page_button)
main_layout.addWidget(browser)
window.setLayout(main_layout)
window.move(0,0)
#window.resize(800,600)
window.show()
sys.exit(app.exec())
