import sys
from PyQt6 import QtWidgets,QtWebEngineWidgets,QtCore
app =QtWidgets.QApplication(sys.argv)

window=QtWidgets.QWidget()
window.setWindowTitle("retumilo")
#label = QtWidgets.QLabel("Hello World!",parent=window)
#label.setWindowTitle("retumilo")
#label.show()
browser=QtWebEngineWidgets.QWebEngineView(parent=window)
browser.load(QtCore.QUrl("https://www.google.com"))
#last_page_button=QtWidgets.QButtonGroup(parent=window).button
back_page_button=QtWidgets.QPushButton("back")#.setGeometry(0,0,100,50)
forward_page_button=QtWidgets.QPushButton("forward")
back_page_button.clicked.connect(browser.back)
forward_page_button.clicked.connect(browser.forward)
layout=QtWidgets.QVBoxLayout()
layout.addWidget(back_page_button)
layout.addWidget(forward_page_button)
layout.addWidget(browser)
window.setLayout(layout)
window.move(0,0)
#window.resize(800,600)
window.show()
sys.exit(app.exec())
